[project]
name = "agio-broker"
version = "0.0.10"
requires-python = ">=3.11"
dependencies = []

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"agio_broker" = [
    "__agio__.yml",
]